/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTradersUnitySDK.Client.OpenAPIDateConverter;

namespace SpaceTradersUnitySDK.Model
{
    /// <summary>
    /// The symbol of the faction.
    /// </summary>
    /// <value>The symbol of the faction.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FactionSymbols
    {
        /// <summary>
        /// Enum COSMIC for value: COSMIC
        /// </summary>
        [EnumMember(Value = "COSMIC")]
        COSMIC = 1,

        /// <summary>
        /// Enum VOID for value: VOID
        /// </summary>
        [EnumMember(Value = "VOID")]
        VOID = 2,

        /// <summary>
        /// Enum GALACTIC for value: GALACTIC
        /// </summary>
        [EnumMember(Value = "GALACTIC")]
        GALACTIC = 3,

        /// <summary>
        /// Enum QUANTUM for value: QUANTUM
        /// </summary>
        [EnumMember(Value = "QUANTUM")]
        QUANTUM = 4,

        /// <summary>
        /// Enum DOMINION for value: DOMINION
        /// </summary>
        [EnumMember(Value = "DOMINION")]
        DOMINION = 5,

        /// <summary>
        /// Enum ASTRO for value: ASTRO
        /// </summary>
        [EnumMember(Value = "ASTRO")]
        ASTRO = 6,

        /// <summary>
        /// Enum CORSAIRS for value: CORSAIRS
        /// </summary>
        [EnumMember(Value = "CORSAIRS")]
        CORSAIRS = 7,

        /// <summary>
        /// Enum OBSIDIAN for value: OBSIDIAN
        /// </summary>
        [EnumMember(Value = "OBSIDIAN")]
        OBSIDIAN = 8,

        /// <summary>
        /// Enum AEGIS for value: AEGIS
        /// </summary>
        [EnumMember(Value = "AEGIS")]
        AEGIS = 9,

        /// <summary>
        /// Enum UNITED for value: UNITED
        /// </summary>
        [EnumMember(Value = "UNITED")]
        UNITED = 10,

        /// <summary>
        /// Enum SOLITARY for value: SOLITARY
        /// </summary>
        [EnumMember(Value = "SOLITARY")]
        SOLITARY = 11,

        /// <summary>
        /// Enum COBALT for value: COBALT
        /// </summary>
        [EnumMember(Value = "COBALT")]
        COBALT = 12,

        /// <summary>
        /// Enum OMEGA for value: OMEGA
        /// </summary>
        [EnumMember(Value = "OMEGA")]
        OMEGA = 13,

        /// <summary>
        /// Enum ECHO for value: ECHO
        /// </summary>
        [EnumMember(Value = "ECHO")]
        ECHO = 14,

        /// <summary>
        /// Enum LORDS for value: LORDS
        /// </summary>
        [EnumMember(Value = "LORDS")]
        LORDS = 15,

        /// <summary>
        /// Enum CULT for value: CULT
        /// </summary>
        [EnumMember(Value = "CULT")]
        CULT = 16,

        /// <summary>
        /// Enum ANCIENTS for value: ANCIENTS
        /// </summary>
        [EnumMember(Value = "ANCIENTS")]
        ANCIENTS = 17,

        /// <summary>
        /// Enum SHADOW for value: SHADOW
        /// </summary>
        [EnumMember(Value = "SHADOW")]
        SHADOW = 18,

        /// <summary>
        /// Enum ETHEREAL for value: ETHEREAL
        /// </summary>
        [EnumMember(Value = "ETHEREAL")]
        ETHEREAL = 19

    }

}
