/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTradersUnitySDK.Client.OpenAPIDateConverter;

namespace SpaceTradersUnitySDK.Model
{
    /// <summary>
    /// GetStatus200ResponseStats
    /// </summary>
    [DataContract(Name = "get_status_200_response_stats")]
    public partial class GetStatus200ResponseStats : IEquatable<GetStatus200ResponseStats>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStatus200ResponseStats" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetStatus200ResponseStats() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStatus200ResponseStats" /> class.
        /// </summary>
        /// <param name="agents">Number of registered agents in the game. (required).</param>
        /// <param name="ships">Total number of ships in the game. (required).</param>
        /// <param name="systems">Total number of systems in the game. (required).</param>
        /// <param name="waypoints">Total number of waypoints in the game. (required).</param>
        public GetStatus200ResponseStats(int agents = default(int), int ships = default(int), int systems = default(int), int waypoints = default(int))
        {
            this.Agents = agents;
            this.Ships = ships;
            this.Systems = systems;
            this.Waypoints = waypoints;
        }

        /// <summary>
        /// Number of registered agents in the game.
        /// </summary>
        /// <value>Number of registered agents in the game.</value>
        [DataMember(Name = "agents", IsRequired = true, EmitDefaultValue = true)]
        public int Agents { get; set; }

        /// <summary>
        /// Total number of ships in the game.
        /// </summary>
        /// <value>Total number of ships in the game.</value>
        [DataMember(Name = "ships", IsRequired = true, EmitDefaultValue = true)]
        public int Ships { get; set; }

        /// <summary>
        /// Total number of systems in the game.
        /// </summary>
        /// <value>Total number of systems in the game.</value>
        [DataMember(Name = "systems", IsRequired = true, EmitDefaultValue = true)]
        public int Systems { get; set; }

        /// <summary>
        /// Total number of waypoints in the game.
        /// </summary>
        /// <value>Total number of waypoints in the game.</value>
        [DataMember(Name = "waypoints", IsRequired = true, EmitDefaultValue = true)]
        public int Waypoints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetStatus200ResponseStats {\n");
            sb.Append("  Agents: ").Append(Agents).Append("\n");
            sb.Append("  Ships: ").Append(Ships).Append("\n");
            sb.Append("  Systems: ").Append(Systems).Append("\n");
            sb.Append("  Waypoints: ").Append(Waypoints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetStatus200ResponseStats);
        }

        /// <summary>
        /// Returns true if GetStatus200ResponseStats instances are equal
        /// </summary>
        /// <param name="input">Instance of GetStatus200ResponseStats to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetStatus200ResponseStats input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Agents == input.Agents ||
                    this.Agents.Equals(input.Agents)
                ) && 
                (
                    this.Ships == input.Ships ||
                    this.Ships.Equals(input.Ships)
                ) && 
                (
                    this.Systems == input.Systems ||
                    this.Systems.Equals(input.Systems)
                ) && 
                (
                    this.Waypoints == input.Waypoints ||
                    this.Waypoints.Equals(input.Waypoints)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Agents.GetHashCode();
                hashCode = (hashCode * 59) + this.Ships.GetHashCode();
                hashCode = (hashCode * 59) + this.Systems.GetHashCode();
                hashCode = (hashCode * 59) + this.Waypoints.GetHashCode();
                return hashCode;
            }
        }

    }

}
