/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTradersUnitySDK.Client.OpenAPIDateConverter;

namespace SpaceTradersUnitySDK.Model
{
    /// <summary>
    /// InstallMount201ResponseDataTransaction
    /// </summary>
    [DataContract(Name = "Install_Mount_201_Response_data_transaction")]
    public partial class InstallMount201ResponseDataTransaction : IEquatable<InstallMount201ResponseDataTransaction>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallMount201ResponseDataTransaction" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InstallMount201ResponseDataTransaction() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallMount201ResponseDataTransaction" /> class.
        /// </summary>
        /// <param name="totalPrice">The total price of the transaction. (required).</param>
        /// <param name="timestamp">The timestamp of the transaction. (required).</param>
        public InstallMount201ResponseDataTransaction(int totalPrice = default(int), DateTime timestamp = default(DateTime))
        {
            this.TotalPrice = totalPrice;
            this.Timestamp = timestamp;
        }

        /// <summary>
        /// The total price of the transaction.
        /// </summary>
        /// <value>The total price of the transaction.</value>
        [DataMember(Name = "totalPrice", IsRequired = true, EmitDefaultValue = true)]
        public int TotalPrice { get; set; }

        /// <summary>
        /// The timestamp of the transaction.
        /// </summary>
        /// <value>The timestamp of the transaction.</value>
        [DataMember(Name = "timestamp", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallMount201ResponseDataTransaction {\n");
            sb.Append("  TotalPrice: ").Append(TotalPrice).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InstallMount201ResponseDataTransaction);
        }

        /// <summary>
        /// Returns true if InstallMount201ResponseDataTransaction instances are equal
        /// </summary>
        /// <param name="input">Instance of InstallMount201ResponseDataTransaction to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InstallMount201ResponseDataTransaction input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TotalPrice == input.TotalPrice ||
                    this.TotalPrice.Equals(input.TotalPrice)
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.TotalPrice.GetHashCode();
                if (this.Timestamp != null)
                {
                    hashCode = (hashCode * 59) + this.Timestamp.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
