/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTradersUnitySDK.Client.OpenAPIDateConverter;

namespace SpaceTradersUnitySDK.Model
{
    /// <summary>
    /// JumpShip200ResponseData
    /// </summary>
    [DataContract(Name = "jump_ship_200_response_data")]
    public partial class JumpShip200ResponseData : IEquatable<JumpShip200ResponseData>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JumpShip200ResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected JumpShip200ResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="JumpShip200ResponseData" /> class.
        /// </summary>
        /// <param name="cooldown">cooldown (required).</param>
        /// <param name="nav">nav (required).</param>
        public JumpShip200ResponseData(Cooldown cooldown = default(Cooldown), ShipNav nav = default(ShipNav))
        {
            // to ensure "cooldown" is required (not null)
            if (cooldown == null)
            {
                throw new ArgumentNullException("cooldown is a required property for JumpShip200ResponseData and cannot be null");
            }
            this.Cooldown = cooldown;
            // to ensure "nav" is required (not null)
            if (nav == null)
            {
                throw new ArgumentNullException("nav is a required property for JumpShip200ResponseData and cannot be null");
            }
            this.Nav = nav;
        }

        /// <summary>
        /// Gets or Sets Cooldown
        /// </summary>
        [DataMember(Name = "cooldown", IsRequired = true, EmitDefaultValue = true)]
        public Cooldown Cooldown { get; set; }

        /// <summary>
        /// Gets or Sets Nav
        /// </summary>
        [DataMember(Name = "nav", IsRequired = true, EmitDefaultValue = true)]
        public ShipNav Nav { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JumpShip200ResponseData {\n");
            sb.Append("  Cooldown: ").Append(Cooldown).Append("\n");
            sb.Append("  Nav: ").Append(Nav).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JumpShip200ResponseData);
        }

        /// <summary>
        /// Returns true if JumpShip200ResponseData instances are equal
        /// </summary>
        /// <param name="input">Instance of JumpShip200ResponseData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JumpShip200ResponseData input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Cooldown == input.Cooldown ||
                    (this.Cooldown != null &&
                    this.Cooldown.Equals(input.Cooldown))
                ) && 
                (
                    this.Nav == input.Nav ||
                    (this.Nav != null &&
                    this.Nav.Equals(input.Nav))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Cooldown != null)
                {
                    hashCode = (hashCode * 59) + this.Cooldown.GetHashCode();
                }
                if (this.Nav != null)
                {
                    hashCode = (hashCode * 59) + this.Nav.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
