/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTradersUnitySDK.Client.OpenAPIDateConverter;

namespace SpaceTradersUnitySDK.Model
{
    /// <summary>
    /// The unique identifier of the trait.
    /// </summary>
    /// <value>The unique identifier of the trait.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WaypointTraitSymbol
    {
        /// <summary>
        /// Enum UNCHARTED for value: UNCHARTED
        /// </summary>
        [EnumMember(Value = "UNCHARTED")]
        UNCHARTED = 1,

        /// <summary>
        /// Enum UNDERCONSTRUCTION for value: UNDER_CONSTRUCTION
        /// </summary>
        [EnumMember(Value = "UNDER_CONSTRUCTION")]
        UNDERCONSTRUCTION = 2,

        /// <summary>
        /// Enum MARKETPLACE for value: MARKETPLACE
        /// </summary>
        [EnumMember(Value = "MARKETPLACE")]
        MARKETPLACE = 3,

        /// <summary>
        /// Enum SHIPYARD for value: SHIPYARD
        /// </summary>
        [EnumMember(Value = "SHIPYARD")]
        SHIPYARD = 4,

        /// <summary>
        /// Enum OUTPOST for value: OUTPOST
        /// </summary>
        [EnumMember(Value = "OUTPOST")]
        OUTPOST = 5,

        /// <summary>
        /// Enum SCATTEREDSETTLEMENTS for value: SCATTERED_SETTLEMENTS
        /// </summary>
        [EnumMember(Value = "SCATTERED_SETTLEMENTS")]
        SCATTEREDSETTLEMENTS = 6,

        /// <summary>
        /// Enum SPRAWLINGCITIES for value: SPRAWLING_CITIES
        /// </summary>
        [EnumMember(Value = "SPRAWLING_CITIES")]
        SPRAWLINGCITIES = 7,

        /// <summary>
        /// Enum MEGASTRUCTURES for value: MEGA_STRUCTURES
        /// </summary>
        [EnumMember(Value = "MEGA_STRUCTURES")]
        MEGASTRUCTURES = 8,

        /// <summary>
        /// Enum PIRATEBASE for value: PIRATE_BASE
        /// </summary>
        [EnumMember(Value = "PIRATE_BASE")]
        PIRATEBASE = 9,

        /// <summary>
        /// Enum OVERCROWDED for value: OVERCROWDED
        /// </summary>
        [EnumMember(Value = "OVERCROWDED")]
        OVERCROWDED = 10,

        /// <summary>
        /// Enum HIGHTECH for value: HIGH_TECH
        /// </summary>
        [EnumMember(Value = "HIGH_TECH")]
        HIGHTECH = 11,

        /// <summary>
        /// Enum CORRUPT for value: CORRUPT
        /// </summary>
        [EnumMember(Value = "CORRUPT")]
        CORRUPT = 12,

        /// <summary>
        /// Enum BUREAUCRATIC for value: BUREAUCRATIC
        /// </summary>
        [EnumMember(Value = "BUREAUCRATIC")]
        BUREAUCRATIC = 13,

        /// <summary>
        /// Enum TRADINGHUB for value: TRADING_HUB
        /// </summary>
        [EnumMember(Value = "TRADING_HUB")]
        TRADINGHUB = 14,

        /// <summary>
        /// Enum INDUSTRIAL for value: INDUSTRIAL
        /// </summary>
        [EnumMember(Value = "INDUSTRIAL")]
        INDUSTRIAL = 15,

        /// <summary>
        /// Enum BLACKMARKET for value: BLACK_MARKET
        /// </summary>
        [EnumMember(Value = "BLACK_MARKET")]
        BLACKMARKET = 16,

        /// <summary>
        /// Enum RESEARCHFACILITY for value: RESEARCH_FACILITY
        /// </summary>
        [EnumMember(Value = "RESEARCH_FACILITY")]
        RESEARCHFACILITY = 17,

        /// <summary>
        /// Enum MILITARYBASE for value: MILITARY_BASE
        /// </summary>
        [EnumMember(Value = "MILITARY_BASE")]
        MILITARYBASE = 18,

        /// <summary>
        /// Enum SURVEILLANCEOUTPOST for value: SURVEILLANCE_OUTPOST
        /// </summary>
        [EnumMember(Value = "SURVEILLANCE_OUTPOST")]
        SURVEILLANCEOUTPOST = 19,

        /// <summary>
        /// Enum EXPLORATIONOUTPOST for value: EXPLORATION_OUTPOST
        /// </summary>
        [EnumMember(Value = "EXPLORATION_OUTPOST")]
        EXPLORATIONOUTPOST = 20,

        /// <summary>
        /// Enum MINERALDEPOSITS for value: MINERAL_DEPOSITS
        /// </summary>
        [EnumMember(Value = "MINERAL_DEPOSITS")]
        MINERALDEPOSITS = 21,

        /// <summary>
        /// Enum COMMONMETALDEPOSITS for value: COMMON_METAL_DEPOSITS
        /// </summary>
        [EnumMember(Value = "COMMON_METAL_DEPOSITS")]
        COMMONMETALDEPOSITS = 22,

        /// <summary>
        /// Enum PRECIOUSMETALDEPOSITS for value: PRECIOUS_METAL_DEPOSITS
        /// </summary>
        [EnumMember(Value = "PRECIOUS_METAL_DEPOSITS")]
        PRECIOUSMETALDEPOSITS = 23,

        /// <summary>
        /// Enum RAREMETALDEPOSITS for value: RARE_METAL_DEPOSITS
        /// </summary>
        [EnumMember(Value = "RARE_METAL_DEPOSITS")]
        RAREMETALDEPOSITS = 24,

        /// <summary>
        /// Enum METHANEPOOLS for value: METHANE_POOLS
        /// </summary>
        [EnumMember(Value = "METHANE_POOLS")]
        METHANEPOOLS = 25,

        /// <summary>
        /// Enum ICECRYSTALS for value: ICE_CRYSTALS
        /// </summary>
        [EnumMember(Value = "ICE_CRYSTALS")]
        ICECRYSTALS = 26,

        /// <summary>
        /// Enum EXPLOSIVEGASES for value: EXPLOSIVE_GASES
        /// </summary>
        [EnumMember(Value = "EXPLOSIVE_GASES")]
        EXPLOSIVEGASES = 27,

        /// <summary>
        /// Enum STRONGMAGNETOSPHERE for value: STRONG_MAGNETOSPHERE
        /// </summary>
        [EnumMember(Value = "STRONG_MAGNETOSPHERE")]
        STRONGMAGNETOSPHERE = 28,

        /// <summary>
        /// Enum VIBRANTAURORAS for value: VIBRANT_AURORAS
        /// </summary>
        [EnumMember(Value = "VIBRANT_AURORAS")]
        VIBRANTAURORAS = 29,

        /// <summary>
        /// Enum SALTFLATS for value: SALT_FLATS
        /// </summary>
        [EnumMember(Value = "SALT_FLATS")]
        SALTFLATS = 30,

        /// <summary>
        /// Enum CANYONS for value: CANYONS
        /// </summary>
        [EnumMember(Value = "CANYONS")]
        CANYONS = 31,

        /// <summary>
        /// Enum PERPETUALDAYLIGHT for value: PERPETUAL_DAYLIGHT
        /// </summary>
        [EnumMember(Value = "PERPETUAL_DAYLIGHT")]
        PERPETUALDAYLIGHT = 32,

        /// <summary>
        /// Enum PERPETUALOVERCAST for value: PERPETUAL_OVERCAST
        /// </summary>
        [EnumMember(Value = "PERPETUAL_OVERCAST")]
        PERPETUALOVERCAST = 33,

        /// <summary>
        /// Enum DRYSEABEDS for value: DRY_SEABEDS
        /// </summary>
        [EnumMember(Value = "DRY_SEABEDS")]
        DRYSEABEDS = 34,

        /// <summary>
        /// Enum MAGMASEAS for value: MAGMA_SEAS
        /// </summary>
        [EnumMember(Value = "MAGMA_SEAS")]
        MAGMASEAS = 35,

        /// <summary>
        /// Enum SUPERVOLCANOES for value: SUPERVOLCANOES
        /// </summary>
        [EnumMember(Value = "SUPERVOLCANOES")]
        SUPERVOLCANOES = 36,

        /// <summary>
        /// Enum ASHCLOUDS for value: ASH_CLOUDS
        /// </summary>
        [EnumMember(Value = "ASH_CLOUDS")]
        ASHCLOUDS = 37,

        /// <summary>
        /// Enum VASTRUINS for value: VAST_RUINS
        /// </summary>
        [EnumMember(Value = "VAST_RUINS")]
        VASTRUINS = 38,

        /// <summary>
        /// Enum MUTATEDFLORA for value: MUTATED_FLORA
        /// </summary>
        [EnumMember(Value = "MUTATED_FLORA")]
        MUTATEDFLORA = 39,

        /// <summary>
        /// Enum TERRAFORMED for value: TERRAFORMED
        /// </summary>
        [EnumMember(Value = "TERRAFORMED")]
        TERRAFORMED = 40,

        /// <summary>
        /// Enum EXTREMETEMPERATURES for value: EXTREME_TEMPERATURES
        /// </summary>
        [EnumMember(Value = "EXTREME_TEMPERATURES")]
        EXTREMETEMPERATURES = 41,

        /// <summary>
        /// Enum EXTREMEPRESSURE for value: EXTREME_PRESSURE
        /// </summary>
        [EnumMember(Value = "EXTREME_PRESSURE")]
        EXTREMEPRESSURE = 42,

        /// <summary>
        /// Enum DIVERSELIFE for value: DIVERSE_LIFE
        /// </summary>
        [EnumMember(Value = "DIVERSE_LIFE")]
        DIVERSELIFE = 43,

        /// <summary>
        /// Enum SCARCELIFE for value: SCARCE_LIFE
        /// </summary>
        [EnumMember(Value = "SCARCE_LIFE")]
        SCARCELIFE = 44,

        /// <summary>
        /// Enum FOSSILS for value: FOSSILS
        /// </summary>
        [EnumMember(Value = "FOSSILS")]
        FOSSILS = 45,

        /// <summary>
        /// Enum WEAKGRAVITY for value: WEAK_GRAVITY
        /// </summary>
        [EnumMember(Value = "WEAK_GRAVITY")]
        WEAKGRAVITY = 46,

        /// <summary>
        /// Enum STRONGGRAVITY for value: STRONG_GRAVITY
        /// </summary>
        [EnumMember(Value = "STRONG_GRAVITY")]
        STRONGGRAVITY = 47,

        /// <summary>
        /// Enum CRUSHINGGRAVITY for value: CRUSHING_GRAVITY
        /// </summary>
        [EnumMember(Value = "CRUSHING_GRAVITY")]
        CRUSHINGGRAVITY = 48,

        /// <summary>
        /// Enum TOXICATMOSPHERE for value: TOXIC_ATMOSPHERE
        /// </summary>
        [EnumMember(Value = "TOXIC_ATMOSPHERE")]
        TOXICATMOSPHERE = 49,

        /// <summary>
        /// Enum CORROSIVEATMOSPHERE for value: CORROSIVE_ATMOSPHERE
        /// </summary>
        [EnumMember(Value = "CORROSIVE_ATMOSPHERE")]
        CORROSIVEATMOSPHERE = 50,

        /// <summary>
        /// Enum BREATHABLEATMOSPHERE for value: BREATHABLE_ATMOSPHERE
        /// </summary>
        [EnumMember(Value = "BREATHABLE_ATMOSPHERE")]
        BREATHABLEATMOSPHERE = 51,

        /// <summary>
        /// Enum THINATMOSPHERE for value: THIN_ATMOSPHERE
        /// </summary>
        [EnumMember(Value = "THIN_ATMOSPHERE")]
        THINATMOSPHERE = 52,

        /// <summary>
        /// Enum JOVIAN for value: JOVIAN
        /// </summary>
        [EnumMember(Value = "JOVIAN")]
        JOVIAN = 53,

        /// <summary>
        /// Enum ROCKY for value: ROCKY
        /// </summary>
        [EnumMember(Value = "ROCKY")]
        ROCKY = 54,

        /// <summary>
        /// Enum VOLCANIC for value: VOLCANIC
        /// </summary>
        [EnumMember(Value = "VOLCANIC")]
        VOLCANIC = 55,

        /// <summary>
        /// Enum FROZEN for value: FROZEN
        /// </summary>
        [EnumMember(Value = "FROZEN")]
        FROZEN = 56,

        /// <summary>
        /// Enum SWAMP for value: SWAMP
        /// </summary>
        [EnumMember(Value = "SWAMP")]
        SWAMP = 57,

        /// <summary>
        /// Enum BARREN for value: BARREN
        /// </summary>
        [EnumMember(Value = "BARREN")]
        BARREN = 58,

        /// <summary>
        /// Enum TEMPERATE for value: TEMPERATE
        /// </summary>
        [EnumMember(Value = "TEMPERATE")]
        TEMPERATE = 59,

        /// <summary>
        /// Enum JUNGLE for value: JUNGLE
        /// </summary>
        [EnumMember(Value = "JUNGLE")]
        JUNGLE = 60,

        /// <summary>
        /// Enum OCEAN for value: OCEAN
        /// </summary>
        [EnumMember(Value = "OCEAN")]
        OCEAN = 61,

        /// <summary>
        /// Enum RADIOACTIVE for value: RADIOACTIVE
        /// </summary>
        [EnumMember(Value = "RADIOACTIVE")]
        RADIOACTIVE = 62,

        /// <summary>
        /// Enum MICROGRAVITYANOMALIES for value: MICRO_GRAVITY_ANOMALIES
        /// </summary>
        [EnumMember(Value = "MICRO_GRAVITY_ANOMALIES")]
        MICROGRAVITYANOMALIES = 63,

        /// <summary>
        /// Enum DEBRISCLUSTER for value: DEBRIS_CLUSTER
        /// </summary>
        [EnumMember(Value = "DEBRIS_CLUSTER")]
        DEBRISCLUSTER = 64,

        /// <summary>
        /// Enum DEEPCRATERS for value: DEEP_CRATERS
        /// </summary>
        [EnumMember(Value = "DEEP_CRATERS")]
        DEEPCRATERS = 65,

        /// <summary>
        /// Enum SHALLOWCRATERS for value: SHALLOW_CRATERS
        /// </summary>
        [EnumMember(Value = "SHALLOW_CRATERS")]
        SHALLOWCRATERS = 66,

        /// <summary>
        /// Enum UNSTABLECOMPOSITION for value: UNSTABLE_COMPOSITION
        /// </summary>
        [EnumMember(Value = "UNSTABLE_COMPOSITION")]
        UNSTABLECOMPOSITION = 67,

        /// <summary>
        /// Enum HOLLOWEDINTERIOR for value: HOLLOWED_INTERIOR
        /// </summary>
        [EnumMember(Value = "HOLLOWED_INTERIOR")]
        HOLLOWEDINTERIOR = 68,

        /// <summary>
        /// Enum STRIPPED for value: STRIPPED
        /// </summary>
        [EnumMember(Value = "STRIPPED")]
        STRIPPED = 69

    }

}
