/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using SpaceTradersUnitySDK.Client;
using SpaceTradersUnitySDK.Model;

namespace SpaceTradersUnitySDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFactionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Faction
        /// </summary>
        /// <remarks>
        /// View the details of a faction.
        /// </remarks>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="factionSymbol">The faction symbol</param>
        /// <returns>GetFaction200Response</returns>
        GetFaction200Response GetFaction(string factionSymbol);

        /// <summary>
        /// Get Faction
        /// </summary>
        /// <remarks>
        /// View the details of a faction.
        /// </remarks>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="factionSymbol">The faction symbol</param>
        /// <returns>ApiResponse of GetFaction200Response</returns>
        ApiResponse<GetFaction200Response> GetFactionWithHttpInfo(string factionSymbol);
        /// <summary>
        /// List Factions
        /// </summary>
        /// <remarks>
        /// List all discovered factions in the game.
        /// </remarks>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">What entry offset to request (optional)</param>
        /// <param name="limit">How many entries to return per page (optional)</param>
        /// <returns>GetFactions200Response</returns>
        GetFactions200Response GetFactions(int? page = default(int?), int? limit = default(int?));

        /// <summary>
        /// List Factions
        /// </summary>
        /// <remarks>
        /// List all discovered factions in the game.
        /// </remarks>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">What entry offset to request (optional)</param>
        /// <param name="limit">How many entries to return per page (optional)</param>
        /// <returns>ApiResponse of GetFactions200Response</returns>
        ApiResponse<GetFactions200Response> GetFactionsWithHttpInfo(int? page = default(int?), int? limit = default(int?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFactionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Faction
        /// </summary>
        /// <remarks>
        /// View the details of a faction.
        /// </remarks>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="factionSymbol">The faction symbol</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetFaction200Response</returns>
        System.Threading.Tasks.Task<GetFaction200Response> GetFactionAsync(string factionSymbol, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Faction
        /// </summary>
        /// <remarks>
        /// View the details of a faction.
        /// </remarks>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="factionSymbol">The faction symbol</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetFaction200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetFaction200Response>> GetFactionWithHttpInfoAsync(string factionSymbol, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List Factions
        /// </summary>
        /// <remarks>
        /// List all discovered factions in the game.
        /// </remarks>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">What entry offset to request (optional)</param>
        /// <param name="limit">How many entries to return per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetFactions200Response</returns>
        System.Threading.Tasks.Task<GetFactions200Response> GetFactionsAsync(int? page = default(int?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List Factions
        /// </summary>
        /// <remarks>
        /// List all discovered factions in the game.
        /// </remarks>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">What entry offset to request (optional)</param>
        /// <param name="limit">How many entries to return per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetFactions200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetFactions200Response>> GetFactionsWithHttpInfoAsync(int? page = default(int?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFactionsApi : IFactionsApiSync, IFactionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FactionsApi : IDisposable, IFactionsApi
    {
        private SpaceTradersUnitySDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FactionsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public FactionsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FactionsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public FactionsApi(string basePath)
        {
            this.Configuration = SpaceTradersUnitySDK.Client.Configuration.MergeConfigurations(
                SpaceTradersUnitySDK.Client.GlobalConfiguration.Instance,
                new SpaceTradersUnitySDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new SpaceTradersUnitySDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = SpaceTradersUnitySDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FactionsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public FactionsApi(SpaceTradersUnitySDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = SpaceTradersUnitySDK.Client.Configuration.MergeConfigurations(
                SpaceTradersUnitySDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new SpaceTradersUnitySDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = SpaceTradersUnitySDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FactionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public FactionsApi(SpaceTradersUnitySDK.Client.ISynchronousClient client, SpaceTradersUnitySDK.Client.IAsynchronousClient asyncClient, SpaceTradersUnitySDK.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = SpaceTradersUnitySDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public SpaceTradersUnitySDK.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public SpaceTradersUnitySDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public SpaceTradersUnitySDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SpaceTradersUnitySDK.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SpaceTradersUnitySDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Faction View the details of a faction.
        /// </summary>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="factionSymbol">The faction symbol</param>
        /// <returns>GetFaction200Response</returns>
        public GetFaction200Response GetFaction(string factionSymbol)
        {
            SpaceTradersUnitySDK.Client.ApiResponse<GetFaction200Response> localVarResponse = GetFactionWithHttpInfo(factionSymbol);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Faction View the details of a faction.
        /// </summary>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="factionSymbol">The faction symbol</param>
        /// <returns>ApiResponse of GetFaction200Response</returns>
        public SpaceTradersUnitySDK.Client.ApiResponse<GetFaction200Response> GetFactionWithHttpInfo(string factionSymbol)
        {
            // verify the required parameter 'factionSymbol' is set
            if (factionSymbol == null)
                throw new SpaceTradersUnitySDK.Client.ApiException(400, "Missing required parameter 'factionSymbol' when calling FactionsApi->GetFaction");

            SpaceTradersUnitySDK.Client.RequestOptions localVarRequestOptions = new SpaceTradersUnitySDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SpaceTradersUnitySDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SpaceTradersUnitySDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("factionSymbol", SpaceTradersUnitySDK.Client.ClientUtils.ParameterToString(factionSymbol)); // path parameter

            // authentication (AgentToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetFaction200Response>("/factions/{factionSymbol}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFaction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Faction View the details of a faction.
        /// </summary>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="factionSymbol">The faction symbol</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetFaction200Response</returns>
        public async System.Threading.Tasks.Task<GetFaction200Response> GetFactionAsync(string factionSymbol, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = GetFactionWithHttpInfoAsync(factionSymbol, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            SpaceTradersUnitySDK.Client.ApiResponse<GetFaction200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            SpaceTradersUnitySDK.Client.ApiResponse<GetFaction200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Faction View the details of a faction.
        /// </summary>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="factionSymbol">The faction symbol</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetFaction200Response)</returns>
        public async System.Threading.Tasks.Task<SpaceTradersUnitySDK.Client.ApiResponse<GetFaction200Response>> GetFactionWithHttpInfoAsync(string factionSymbol, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'factionSymbol' is set
            if (factionSymbol == null)
                throw new SpaceTradersUnitySDK.Client.ApiException(400, "Missing required parameter 'factionSymbol' when calling FactionsApi->GetFaction");


            SpaceTradersUnitySDK.Client.RequestOptions localVarRequestOptions = new SpaceTradersUnitySDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SpaceTradersUnitySDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SpaceTradersUnitySDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("factionSymbol", SpaceTradersUnitySDK.Client.ClientUtils.ParameterToString(factionSymbol)); // path parameter

            // authentication (AgentToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<GetFaction200Response>("/factions/{factionSymbol}", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFaction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Factions List all discovered factions in the game.
        /// </summary>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">What entry offset to request (optional)</param>
        /// <param name="limit">How many entries to return per page (optional)</param>
        /// <returns>GetFactions200Response</returns>
        public GetFactions200Response GetFactions(int? page = default(int?), int? limit = default(int?))
        {
            SpaceTradersUnitySDK.Client.ApiResponse<GetFactions200Response> localVarResponse = GetFactionsWithHttpInfo(page, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Factions List all discovered factions in the game.
        /// </summary>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">What entry offset to request (optional)</param>
        /// <param name="limit">How many entries to return per page (optional)</param>
        /// <returns>ApiResponse of GetFactions200Response</returns>
        public SpaceTradersUnitySDK.Client.ApiResponse<GetFactions200Response> GetFactionsWithHttpInfo(int? page = default(int?), int? limit = default(int?))
        {
            SpaceTradersUnitySDK.Client.RequestOptions localVarRequestOptions = new SpaceTradersUnitySDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SpaceTradersUnitySDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SpaceTradersUnitySDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(SpaceTradersUnitySDK.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(SpaceTradersUnitySDK.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (AgentToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetFactions200Response>("/factions", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFactions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Factions List all discovered factions in the game.
        /// </summary>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">What entry offset to request (optional)</param>
        /// <param name="limit">How many entries to return per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetFactions200Response</returns>
        public async System.Threading.Tasks.Task<GetFactions200Response> GetFactionsAsync(int? page = default(int?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = GetFactionsWithHttpInfoAsync(page, limit, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            SpaceTradersUnitySDK.Client.ApiResponse<GetFactions200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            SpaceTradersUnitySDK.Client.ApiResponse<GetFactions200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Factions List all discovered factions in the game.
        /// </summary>
        /// <exception cref="SpaceTradersUnitySDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">What entry offset to request (optional)</param>
        /// <param name="limit">How many entries to return per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetFactions200Response)</returns>
        public async System.Threading.Tasks.Task<SpaceTradersUnitySDK.Client.ApiResponse<GetFactions200Response>> GetFactionsWithHttpInfoAsync(int? page = default(int?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            SpaceTradersUnitySDK.Client.RequestOptions localVarRequestOptions = new SpaceTradersUnitySDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SpaceTradersUnitySDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SpaceTradersUnitySDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(SpaceTradersUnitySDK.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(SpaceTradersUnitySDK.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (AgentToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<GetFactions200Response>("/factions", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFactions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
