/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpaceTradersUnitySDK.Api;
using SpaceTradersUnitySDK.Model;
using SpaceTradersUnitySDK.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace SpaceTradersUnitySDK.Test.Model
{
    /// <summary>
    ///  Class for testing Contract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContractTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Contract
        //private Contract instance;

        public ContractTests()
        {
            // TODO uncomment below to create an instance of Contract
            //instance = new Contract();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Contract
        /// </summary>
        [Test]
        public void ContractInstanceTest()
        {
            // TODO uncomment below to test "IsType" Contract
            //Assert.IsType<Contract>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FactionSymbol'
        /// </summary>
        [Test]
        public void FactionSymbolTest()
        {
            // TODO unit test for the property 'FactionSymbol'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Terms'
        /// </summary>
        [Test]
        public void TermsTest()
        {
            // TODO unit test for the property 'Terms'
        }
        /// <summary>
        /// Test the property 'Accepted'
        /// </summary>
        [Test]
        public void AcceptedTest()
        {
            // TODO unit test for the property 'Accepted'
        }
        /// <summary>
        /// Test the property 'Fulfilled'
        /// </summary>
        [Test]
        public void FulfilledTest()
        {
            // TODO unit test for the property 'Fulfilled'
        }
        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Test]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }
    }
}
