/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpaceTradersUnitySDK.Api;
using SpaceTradersUnitySDK.Model;
using SpaceTradersUnitySDK.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace SpaceTradersUnitySDK.Test.Model
{
    /// <summary>
    ///  Class for testing GetStatus200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetStatus200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetStatus200Response
        //private GetStatus200Response instance;

        public GetStatus200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetStatus200Response
            //instance = new GetStatus200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetStatus200Response
        /// </summary>
        [Test]
        public void GetStatus200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetStatus200Response
            //Assert.IsType<GetStatus200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Test]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'ResetDate'
        /// </summary>
        [Test]
        public void ResetDateTest()
        {
            // TODO unit test for the property 'ResetDate'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Test]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
        /// <summary>
        /// Test the property 'Leaderboards'
        /// </summary>
        [Test]
        public void LeaderboardsTest()
        {
            // TODO unit test for the property 'Leaderboards'
        }
        /// <summary>
        /// Test the property 'ServerResets'
        /// </summary>
        [Test]
        public void ServerResetsTest()
        {
            // TODO unit test for the property 'ServerResets'
        }
        /// <summary>
        /// Test the property 'Announcements'
        /// </summary>
        [Test]
        public void AnnouncementsTest()
        {
            // TODO unit test for the property 'Announcements'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
    }
}
