/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpaceTradersUnitySDK.Api;
using SpaceTradersUnitySDK.Model;
using SpaceTradersUnitySDK.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace SpaceTradersUnitySDK.Test.Model
{
    /// <summary>
    ///  Class for testing ScannedShip
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScannedShipTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScannedShip
        //private ScannedShip instance;

        public ScannedShipTests()
        {
            // TODO uncomment below to create an instance of ScannedShip
            //instance = new ScannedShip();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScannedShip
        /// </summary>
        [Test]
        public void ScannedShipInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScannedShip
            //Assert.IsType<ScannedShip>(instance);
        }

        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Registration'
        /// </summary>
        [Test]
        public void RegistrationTest()
        {
            // TODO unit test for the property 'Registration'
        }
        /// <summary>
        /// Test the property 'Nav'
        /// </summary>
        [Test]
        public void NavTest()
        {
            // TODO unit test for the property 'Nav'
        }
        /// <summary>
        /// Test the property 'Frame'
        /// </summary>
        [Test]
        public void FrameTest()
        {
            // TODO unit test for the property 'Frame'
        }
        /// <summary>
        /// Test the property 'Reactor'
        /// </summary>
        [Test]
        public void ReactorTest()
        {
            // TODO unit test for the property 'Reactor'
        }
        /// <summary>
        /// Test the property 'Engine'
        /// </summary>
        [Test]
        public void EngineTest()
        {
            // TODO unit test for the property 'Engine'
        }
        /// <summary>
        /// Test the property 'Mounts'
        /// </summary>
        [Test]
        public void MountsTest()
        {
            // TODO unit test for the property 'Mounts'
        }
    }
}
